name: DeepReadMapper
channels:
  - conda-forge
  - defaults
dependencies:
  # Build tools
  - cxx-compiler  # Provides g++/gcc
  - zig # Build

  # Core dependencies
  - openvino
  - faiss-cpu
  - zlib
  - llvm-openmp
  - libopenblas=*=*openmp* # Ensure OpenBLAS is built with OpenMP support
  - cereal

  # Linting and formatting
  - pre-commit
